### ISSUE TITLE
Buy Sean new pants

### ISSUE THREAD

**Issue by mkosmala** [mkosmala/all-the-things#105]

**Comment by bhardt8** [comment]
Ordered and received. One worked and fit. Reordered 3 more in a better size. Returning the rest.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bhardt8** [comment]
Two of them were good. I am closing this as I think he will have enough

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
