### ISSUE TITLE
Get Sean's hood zipper replaced

### ISSUE THREAD

**Issue by mkosmala** [mkosmala/all-the-things#242]
M to call around and find a place
B to do drop-off

**Comment by bhardt8** [comment]
8.5 inch YKK

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bhardt8** [comment]
Temporary fix made so it will not separate. Also means we can’t remove hood anymore 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
