### ISSUE TITLE
Make appointment for 45,000 mile checkup

### ISSUE THREAD

**Issue by mkosmala** [mkosmala/all-the-things#72]

**Comment by bhardt8** [comment]
Scheduled for Oct 4. Drop off at 7:15. Will get loaner vehicle

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bhardt8** [comment]
Written on calendar 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mkosmala** [comment]
Sorry, need to reschedule
