### ISSUE TITLE
Make copy - Get copy of new front door key to Roseann

### ISSUE THREAD

**Issue by mkosmala** [mkosmala/all-the-things#78]

**Comment by bhardt8** [comment]
Put in the mail on Oct 1

**Comment by mkosmala** [comment]
Mail didn't work.
Make new copy of key

**Comment by bhardt8** [comment]
Copy made. Will hold for Roseann

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bhardt8** [comment]
Emailed Roseann to let her know where to find the key

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
