### ISSUE TITLE
Contact BNS about Kyle staying later on Mika's vacation week

### ISSUE THREAD

**Issue by mkosmala** [mkosmala/all-the-things#8]

**Comment by bhardt8** [comment]
I set myself a reminder to call tomorrow when I arrive at work. Should be updated to closed by end of day tomorrow.

**Comment by bhardt8** [comment]
Stay until 3 pm MWTh, extended day on F, regular on T

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
